### ISSUE TITLE
Problem with latest update

### ISSUE THREAD

**Issue by mignat** [mhadam/clutch#28]
> Transmission version : 3.0.0
> transmission-clutch version : 5.0.0

On the latest version i get the following error using accessor. ( works on 4.2.2 )
Tested on both Windows and Linux

My code :
```
from clutch import Client

client = Client(address="http://192.168.88.100:9091/transmission/rpc")
torrentlist = client.torrent.accessor(fields=['id', 'files']).dict(exclude_none=True)
print(torrentlist)
```

ERROR: 

```
Traceback (most recent call last):
  File "C:\Users\Dark\Desktop\test.py", line 4, in <module>
    client.torrent.accessor(fields=['id', 'files']).dict(exclude_none=True)
  File "C:\Users\Dark\AppData\Roaming\Python\Python39\site-packages\clutch\method\torrent.py", line 42, in accessor
    return self._connection.send(
  File "C:\Users\Dark\AppData\Roaming\Python\Python39\site-packages\clutch\network\connection.py", line 30, in send
    return Response[model].parse_raw(response.text)  # type: ignore
  File "pydantic\main.py", line 538, in pydantic.main.BaseModel.parse_raw
  File "pydantic\main.py", line 515, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 70 validation errors for Response[TorrentAccessorResponse]
arguments -> torrents -> 0 -> activity_date
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> added_date
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> bandwidth_priority
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> comment
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> corrupt_ever
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> creator
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> date_created
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> desired_available
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> done_date
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> download_dir
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> downloaded_ever
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> download_limit
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> download_limited
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> edit_date
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> error
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> error_string
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> eta
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> eta_idle
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> file_stats
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> hash_string
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> have_unchecked
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> have_valid
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> honors_session_limits
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> is_finished
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> is_private
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> is_stalled
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> labels
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> left_until_done
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> magnet_link
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> manual_announce_time
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> max_connected_peers
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> metadata_percent_complete
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> name
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> peer_limit
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> peers
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> peers_connected
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> peers_from
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> peers_getting_from_us
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> peers_sending_to_us
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> percent_done
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> pieces
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> piece_count
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> piece_size
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> priorities
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> queue_position
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> rate_download
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> rate_upload
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> recheck_progress
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> seconds_downloading
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> seconds_seeding
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> seed_idle_limit
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> seed_idle_mode
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> seed_ratio_limit
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> seed_ratio_mode
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> size_when_done
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> start_date
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> status
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> trackers
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> tracker_stats
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> total_size
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> torrent_file
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> uploaded_ever
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> upload_limit
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> upload_limited
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> upload_ratio
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> wanted
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> webseeds
  field required (type=value_error.missing)
arguments -> torrents -> 0 -> webseeds_sending_to_us
  field required (type=value_error.missing)
arguments -> torrents -> 0
  value is not a valid sequence (type=type_error.sequence)
arguments -> torrents -> 0
  value is not a valid sequence (type=type_error.sequence)

**Comment by mhadam** [comment]
Sorry about that - it should be fixed in 5.0.1!

**Comment by mhadam** [comment]
I'm going to close this out, please let me know if you have any other issue.

**Comment by mignat** [comment]
@mhadam Thank you for the fix, it is working now !
